import { createReadStream } from "node:fs";
import { mkdir, stat, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
import type { Response } from "express";
import { BlobNotFoundError, del, get, put } from "@vercel/blob";
import { config } from "./config.js";
import { assert, HttpError } from "./errors.js";

// Keys are generated by the application. Never accept a URL or a filesystem path
// from a client, even when the backing store changes.
function storageKey(key: string) {
  assert(
    /^[a-z0-9][a-z0-9._-]{0,99}$/i.test(key) && !key.includes(".."),
    422,
    "Invalid file reference.",
  );
  return key;
}

function storageError(error: unknown): never {
  if (
    error instanceof BlobNotFoundError ||
    (error as NodeJS.ErrnoException)?.code === "ENOENT"
  )
    throw new HttpError(404, "This file is no longer available.");
  if (error instanceof HttpError) throw error;
  throw new HttpError(
    503,
    "File storage is temporarily unavailable. Please try again shortly.",
  );
}

export async function writeStoredFile(
  key: string,
  bytes: Buffer,
  contentType: string,
) {
  storageKey(key);
  try {
    if (config.fileStorage === "blob") {
      await put(key, bytes, {
        access: "private",
        token: config.blobToken,
        contentType,
        addRandomSuffix: false,
        allowOverwrite: false,
      });
    } else {
      await mkdir(config.uploadDir, { recursive: true });
      await writeFile(path.join(config.uploadDir, key), bytes, {
        flag: "wx",
        mode: 0o600,
      });
    }
  } catch (error) {
    storageError(error);
  }
}

async function storedStream(key: string) {
  storageKey(key);
  try {
    if (config.fileStorage === "blob") {
      const result = await get(key, {
        access: "private",
        token: config.blobToken,
        useCache: false,
      });
      assert(
        result?.statusCode === 200,
        404,
        "This file is no longer available.",
      );
      return {
        size: result.blob.size,
        stream: Readable.fromWeb(result.stream as any),
      };
    }
    const filename = path.join(config.uploadDir, key);
    const info = await stat(filename);
    return { size: info.size, stream: createReadStream(filename) };
  } catch (error) {
    storageError(error);
  }
}

export async function readStoredFile(key: string, limit = 10 * 1024 * 1024) {
  const file = await storedStream(key);
  if (file.size > limit) {
    file.stream.destroy();
    throw new HttpError(413, "The file exceeds the permitted size.");
  }
  const chunks: Buffer[] = [];
  let size = 0;
  try {
    for await (const chunk of file.stream) {
      const bytes = Buffer.from(chunk);
      size += bytes.length;
      assert(size <= limit, 413, "The file exceeds the permitted size.");
      chunks.push(bytes);
    }
    return Buffer.concat(chunks, size);
  } catch (error) {
    file.stream.destroy();
    storageError(error);
  }
}

// Stream private downloads through the authorized API. Streaming also avoids
// buffering a 10 MB PDF inside a Vercel function response.
export async function sendStoredFile(
  res: Response,
  key: string,
  contentType: string,
  downloadName?: string,
) {
  const file = await storedStream(key);
  if (downloadName) res.attachment(downloadName);
  res.type(contentType);
  res.setHeader("Content-Length", file.size);
  res.flushHeaders();
  await pipeline(file.stream, res);
}

export async function deleteStoredFile(key: string) {
  storageKey(key);
  try {
    if (config.fileStorage === "blob")
      await del(key, { token: config.blobToken });
    else await unlink(path.join(config.uploadDir, key));
  } catch (error) {
    if (
      error instanceof BlobNotFoundError ||
      (error as NodeJS.ErrnoException)?.code === "ENOENT"
    )
      return;
    storageError(error);
  }
}
