import {
  Boxes,
  BriefcaseBusiness,
  Building2,
  CircleDollarSign,
  ClipboardCheck,
  ClipboardList,
  Code2,
  FileCheck2,
  FileClock,
  FileSignature,
  FileSpreadsheet,
  FileText,
  Handshake,
  Headphones,
  Layers3,
  Package,
  Receipt,
  Send,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Target,
  Truck,
  UserRoundCheck,
  UsersRound,
  Video,
  Wallet,
  Wrench,
} from "lucide-react";
import type { Module, OrganizationType } from "../../shared/domain";
export const moduleIcons = {
  requirements: ClipboardList,
  rfqs: Send,
  quotations: FileSpreadsheet,
  orders: ShoppingCart,
  deliveries: Truck,
  contracts: FileSignature,
  invoices: Receipt,
  payments: Wallet,
  catalog: Package,
  candidates: UsersRound,
  interviews: Video,
  engagements: BriefcaseBusiness,
  timesheets: FileClock,
  milestones: Target,
  demos: Sparkles,
  performance: CircleDollarSign,
  tickets: Headphones,
} satisfies Record<Module, any>;
export const organizationIcons = {
  vendor: Building2,
  supplier: Boxes,
  client: ShoppingCart,
  recruitment: UsersRound,
  staffing: BriefcaseBusiness,
  service_provider: Wrench,
  technology_partner: Code2,
  business_partner: Handshake,
  other: Layers3,
} satisfies Record<OrganizationType, any>;
