export const demoPassword = "PartnerHub@2026";
export const demoAccounts = [
  {
    key: "admin",
    name: "Arjun Mehta",
    email: "admin@vs.example",
    role: "super_admin",
    label: "Super Admin",
    description: "The complete platform, in one view",
  },
  {
    key: "buyer",
    name: "Priya Sharma",
    email: "buyer@acme.example",
    role: "org_admin",
    type: "client",
    label: "Client / Buyer",
    description: "Source, compare and procure",
  },
  {
    key: "vendor",
    name: "Karan Malhotra",
    email: "vendor@nexora.example",
    role: "org_admin",
    type: "vendor",
    label: "Vendor",
    description: "Turn opportunities into orders",
  },
  {
    key: "supplier",
    name: "Sneha Rao",
    email: "supplier@meridian.example",
    role: "org_admin",
    type: "supplier",
    label: "Supplier",
    description: "Catalog, orders and deliveries",
  },
  {
    key: "recruiter",
    name: "Riya Kapoor",
    email: "recruiter@talentbridge.example",
    role: "org_admin",
    type: "recruitment",
    label: "Recruitment",
    description: "Follow every candidate journey",
  },
  {
    key: "staffing",
    name: "Aditya Desai",
    email: "staffing@flexforce.example",
    role: "org_admin",
    type: "staffing",
    label: "Staffing",
    description: "Deployments and timesheets",
  },
  {
    key: "service",
    name: "Nisha Iyer",
    email: "services@aster.example",
    role: "org_admin",
    type: "service_provider",
    label: "Service Provider",
    description: "Projects, milestones and billing",
  },
  {
    key: "technology",
    name: "Dev Patel",
    email: "technology@cloudcraft.example",
    role: "org_admin",
    type: "technology_partner",
    label: "Technology Partner",
    description: "Solutions, integrations and demos",
  },
  {
    key: "business",
    name: "Aarav Joshi",
    email: "partner@bridgeworks.example",
    role: "org_admin",
    type: "business_partner",
    label: "Business Partner",
    description: "Build new collaborations",
  },
  {
    key: "other",
    name: "Ishita Sen",
    email: "partner@horizon.example",
    role: "org_admin",
    type: "other",
    label: "Other Organization",
    description: "A flexible partner workspace",
  },
  {
    key: "verification",
    name: "Neha Kapoor",
    email: "verification@vs.example",
    role: "verification",
    label: "Verification Team",
    description: "Company and document review",
  },
  {
    key: "procurement",
    name: "Priya Nair",
    email: "procurement@vs.example",
    role: "procurement",
    label: "Procurement Team",
    description: "Oversee the sourcing lifecycle",
  },
  {
    key: "finance",
    name: "Rohan Shah",
    email: "finance@vs.example",
    role: "finance",
    label: "Finance Team",
    description: "Invoice approvals and payments",
  },
  {
    key: "hr",
    name: "Ananya Rao",
    email: "hr@vs.example",
    role: "hr",
    label: "HR & Recruitment",
    description: "Requirements, interviews and offers",
  },
  {
    key: "management",
    name: "Vijay Kumar",
    email: "management@vs.example",
    role: "management",
    label: "Management",
    description: "A clear view of business performance",
  },
  {
    key: "support",
    name: "Tara Menon",
    email: "support@vs.example",
    role: "support",
    label: "Support Team",
    description: "Help every partner move forward",
  },
];
